### ISSUE TITLE
QEMU Bootloop after completing 4.3

### ISSUE THREAD

**Issue by Artillect** [intermezzOS/kernel#103]
After completing [Chapter 4.3](http://intermezzos.github.io/book/jumping-headlong-into-long-mode.html) and running my code using make, QEMU starts flashing between:

```
SeaBIOS (version 1.7.4-20150827_223240-lgw01-56)


       iPXE (http://ipxe.org) 00:03.0 C900 PCI2.10 PnP PMM+07FC10F0+07F210F0 C900



       Booting from Hard Disk...
       Boot failed: could not read the boot disk

       Booting from Floppy...
       Boot failed: could not read the boot disk

       Booting from DVD/CD...
```
and
``VGA Blank mode``

What can I do to fix this?

**Comment by steveklabnik** [comment]
I have not seen this before! What platform are you on? I wonder if any of the things on http://intermezzos.github.io/book/appendix/troubleshooting.html would help you, even though none of them match exactly.

**Comment by Artillect** [comment]
I went through everything that I've done and verified that my code was correct, I'm pretty sure that I didn't end up changing anything, but it works now.

**Comment by Artillect** [comment]
I went through everything that I've done and verified that my code was correct, I'm pretty sure that I didn't end up changing anything, but it works now.

**Comment by steveklabnik** [comment]
Okay! Glad it's working 👍
