### ISSUE TITLE
rust-x86 needs version bumping

### ISSUE THREAD

**Issue by Thetoxicarcade** [intermezzOS/kernel#108]
https://github.com/gz/rust-x86/pull/27 - issues in Rust (rust-x86) compiling needed updating.

Can we bump the rust-x86 version?

**Comment by steveklabnik** [comment]
yes! I'd happily take a PR for this, or whenever I get around to some time to hack on the kernel, I'll take care of it.

**Comment by Thetoxicarcade** [comment]
Cool :D
