### ISSUE TITLE
relocation R_X86_64_32 against `.bss' can not be used when making a shared object; recompile with -fPIC

### ISSUE THREAD

**Issue by p-kraszewski** [intermezzOS/kernel#110]
If compilation gives something like:

```
  = note: /usr/bin/ld: /storage/Projects/IntermezzOS_bare/target/x86_64-unknown-intermezzos-gnu/release/build/intermezzos-8ccbbf2f886be67d/out/libboot.a(boot.o): relocation R_X86_64_32 against `.bss' can not be used when making a shared object; recompile with -fPIC
          /usr/bin/ld: final link failed: Nie da się wyświetlić sekcji na wyjściu!
          collect2: error: ld returned 1 exit status

```
this is due to hardened compiler chain: at least on Hardened-Gentoo and Ubuntu 16.10+.

To fix it, you need to change `x86_64-unknown-intermezzos-gnu.json` by adding `"-no-pie"` to `"pre-link-args"`. This will disable hardening for the project.

Hope this helps!

**Comment by steveklabnik** [comment]
Thanks! I'm confused as to why a "hardened" gcc wouldn't want PIE.

**Comment by p-kraszewski** [comment]
Oh, it's the other way around. Hardened GCC wants PIC in so many places, that it can't be easily fulfilled due to conflicts between 32/64 bits. I had the same situation with Haskell/stack on Ubuntu 16.10 - it refused to compile with quite the similar error. That's what pointed me in the right direction with Rust/IntermezzOS.
