### ISSUE TITLE
Closing qemu Cleanly

### ISSUE THREAD

**Issue by rylev** [intermezzOS/kernel#12]
I can't seem to find a good way to cleanly shut down qemu. The docs I found here (http://wiki.qemu.org/download/qemu-doc.html) show a way to "Exit emulator", but this doesn't seem to work for me at least inside of the Vagrant VM. For now, I'm just using `pgrep qemu |  xargs kill -15`

**Comment by steveklabnik** [comment]
It didn't work for me in not-a-vm either. Hmm.

**Comment by henrikhodne** [comment]
Ctrl-C in the terminal that's running qemu does the trick for me. Ctrl-A, X only works in “nographics" mode, which we're not using. You can also do Ctrl-Alt-2 in the qemu window to bring up the monitor and enter `quit`.

**Comment by steveklabnik** [comment]
Ah ha!

**Comment by rylev** [comment]
Hmmm neither works for me running on Mac using the VM specified in the vagrant file.

**Comment by lulezi** [comment]
I ran into this issue as well. @rylev, thanks for `pgrep qemu | xargs kill -15`. Also, I don't know if this is related but when I try to start qemu with `qemu-system-x86_64 -cdrom os.iso` it exits saying `Could not initialize SDL(No available video device) - exiting`. This can be avoided using the `-curses` flag.

**Comment by BrendanBuono** [comment]
As a note, Ctrl-Alt didn't work for me, I had to use Esc instead

**Comment by ljcusack** [comment]
```Esc+2``` ( or ```alt+2``` ) works for me. This switches consoles where you can use the ```quit``` command

**Comment by steveklabnik** [comment]
So, I'm gonna say that we should mention that `alt-2` + `quit` works, and that this is a book issue. Moving it over to that repo!
