### ISSUE TITLE
GCC 5 won't compile with Xcode 9

### ISSUE THREAD

**Issue by andyfangdz** [intermezzOS/kernel#120]
When running the install script provided for macOS, the following error occurred when compiling gcc-5:

```
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/functional:1398:2: error:
      no member named 'fancy_abort' in namespace 'std::__1'; did you mean
      simply 'fancy_abort'?
        _VSTD::abort();
        ^~~~~~~
```

There's already a bug filed for gcc here: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=81037, however that issue is practically considered Won't Fix: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=81037#c14

> gcc-5-branch is now closed and gcc-6-branch is fixed, so closing this as FIXED.

**Comment by steveklabnik** [comment]
Gah. I don't have an OS X machine, so i can't test out any changes. I'd be very happy if someone coudl see if this works for GCC 6!

**Comment by andyfangdz** [comment]
I've only done this up to finishing chapter 4, but it seems to be working so far. I'll create a PR for GCC 6.

**Comment by steveklabnik** [comment]
Merged the change! Thanks a ton :)
