### ISSUE TITLE
Running IntermezzOS on nightly fails to find Xargo target specification

### ISSUE THREAD

**Issue by leocassarani** [intermezzOS/kernel#121]
Hello!

I've been trying to run IntermezzOS on my Mac. After installing all dependencies, I ran `make run` and got the following output (cut down to the offending command):

```
$ xargo build --release --target x86_64-unknown-intermezzos-gnu
error: Error loading target specification: Could not find specification for target "x86_64-unknown-intermezzos-gnu"
  |
  = help: Use `--print target-list` for a list of built-in targets
```

After some digging around, I found [this Xargo issue](https://github.com/japaric/xargo/issues/186) which seemed to suggest that I had to set the `RUST_TARGET_PATH` environment variable.

I then tried running `RUST_TARGET_PATH=$(pwd) xargo build --release --target x86_64-unknown-intermezzos-gnu`, and IntermezzOS built successfully to completion.

The simple fix, therefore, would seem to be forcing the value of that env var in the Makefile, but as I don't fully understand what is going on here, I'm going to leave that up to someone who does.

**Comment by johnterickson** [comment]
Thanks for the workaround!
