### ISSUE TITLE
[Question] IRC/group to discuss about the project?

### ISSUE THREAD

**Issue by k0pernicus** [intermezzOS/kernel#57]
I'm trying to implement my own VGA driver myself.  
I made a simple solution using a macro, like the example given at the end of the chapter `kmain`, but I have a LOT of questions to perform myself in Rust :-)

Is an IRC/channel/group exists to discuss about that?

Thanks a lot!

**Comment by rjgoldsborough** [comment]
@k0pernicus there is an #intermezzos channel on irc.freenode.net

**Comment by k0pernicus** [comment]
Thanks @rjgoldsborough :-)

**Comment by steveklabnik** [comment]
It can be quiet at times, but I'm on 24/7, and try to answer when I come back. `#rust-osdev` on Mozilla's IRC can also be helpful.

Giving it a close since your question was answered!
