### ISSUE TITLE
Installation of specific rustc version fails

### ISSUE THREAD

**Issue by adrianbrink** [intermezzOS/kernel#59]
When running `rustup install nightly-2016-05-26` on macOS 10.12 with all updates applied, the command never exists.

It prints:

```
adrianbrink@ab-mbp:~|⇒  rustup install nightly-2016-05-26
info: syncing channel updates for 'nightly-2016-05-26-x86_64-apple-darwin'
info: downloading component 'rustc'
 42.1 MiB /  42.1 MiB (100 %)   1.8 MiB/s ETA:   0 s
info: downloading component 'rust-std'
 55.1 MiB /  55.1 MiB (100 %) 768.0 KiB/s ETA:   0 s
info: downloading component 'rust-docs'
  6.5 MiB /   6.5 MiB (100 %)   1.0 MiB/s ETA:   0 s
info: downloading component 'cargo'
  2.7 MiB /   2.7 MiB (100 %)   1.2 MiB/s ETA:   0 s
info: installing component 'rustc'
info: installing component 'rust-std'
info: installing component 'rust-docs'
info: installing component 'cargo'
```

And just hangs there forever. The same problem exists for `nightly-2016-05-27`, which I guess means that it fails for this installation method. 

Is there any quick fix for this, until rustup.rs fixes this.

I'm also going to raise an issue there.

**Comment by steveklabnik** [comment]
Hmmmmmmmmm I bet you could do this:

1. Go to rust-lang.org
2. Go to the install page, IIRC (I'm on my phone) it's under "other installs"
3. Right click the link for nightly and copy it
4. Paste it in your browser, but fix the date
5. Use that installer

You'll have to uninstall it once rustup is fixed, but it should get you going in the meantime. Hope that helps!

**Comment by adrianbrink** [comment]
Thanks, I'll try that :-)

**Comment by adrianbrink** [comment]
Mh, the only link I can find for the nightly build is this one: `https://static.rust-lang.org/dist/rust-nightly-x86_64-unknown-linux-gnu.tar.gz` and it comes from here: `https://www.rust-lang.org/en-US/downloads.html`.

However when I amend the first link with the specific date like so: `https://static.rust-lang.org/dist/rust-nightly-2016-05-26-x86_64-unknown-linux-gnu.tar.gz` I get an error that the specified version does not exist. :-(

`This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Key>
dist/rust-nightly-2016-05-26-x86_64-unknown-linux-gnu.tar.gz
</Key>
<RequestId>F1055D9D0B1B1BB6</RequestId>
<HostId>
tRSjDzsyEeD9g54uQ2ozvNzP9zw1dPMSYc3s/sLo5GDNzTBUJyfHXrnj0EGZQyDcnTI1duntdmo=
</HostId>
</Error>`

Was that the trick you meant @steveklabnik ?

**Comment by steveklabnik** [comment]
So, I'm not sure why this was caused, but with the latest changes, it works on any nightly. Or rather, it will at least work on the nightly of each commit; we're no longer using a special fork of libcore that's set up for a specific nightly.

So, @adrianbrink , can you give it a try with the latest nightly instead?

**Comment by steveklabnik** [comment]
We now don't require a specific rust. @adrianbrink let me know if you still are struggling but this specific issues should be gone.
