### ISSUE TITLE
Virtual Machine for Development

### ISSUE THREAD

**Issue by rylev** [intermezzOS/kernel#6]
Speaking with @steveklabnik we both came to the conclusion that only supporting a linux development environment is probably the best thing to do (at least to begin with). I've started trying to get the kernel running in a Linux Virtual Box VM using @ashleygwilliams Vagrantfile from a similar project (per @steveklabnik's suggestion). I've run into a few issues, which I'll hopefully have sorted out soon. I'll have a PR ready when I can find sometime through the holiday season obligations.

**Comment by ashleygwilliams** [comment]
hi! i was actually about to make a PR with my vagrantfile-- would it be stepping on your toes to do that and then have you correct/improve it? i'd love the diff so i can fix my own setup

**Comment by rylev** [comment]
We have a Vagrantfile merged into master through: https://github.com/intermezzOS/kernel/pull/7. It's not yet perfect for reasons elaborated on in the PR.

**Comment by steveklabnik** [comment]
Given that the Vagrantfile was merged, giving a close.
