### ISSUE TITLE
README is out of date

### ISSUE THREAD

**Issue by steveklabnik** [intermezzOS/kernel#70]
It doesn't mention that you need `xargo`.

**Comment by slayerjain** [comment]
Made some changes :)

**Comment by steveklabnik** [comment]
@slayerjain oh?

**Comment by slayerjain** [comment]
@steveklabnik  I think the pull request for this issue should be merged.
btw I have some interesting proposal for file-systems and paging :D

**Comment by steveklabnik** [comment]
This has now been fixed https://github.com/intermezzOS/kernel#building
