### ISSUE TITLE
Cleanup PIC crate

### ISSUE THREAD

**Issue by steveklabnik** [intermezzOS/kernel#74]
The PIC crate is kind of a hack. It'd be nice to fix it up.
- [ ] Use x86 instead of inline asm for `outb`/`inb`
- [ ]  Is this list of functions right? What would a good interface for a PIC be?

**Comment by steveeJ** [comment]
There's a crate for the most common PIC: https://crates.io/crates/pic8259_simple.
Would you want to use this inside the PIC crate or as a replacement?

**Comment by steveklabnik** [comment]
Sure, if it supports all the stuff we need; I haven't looked at it.
