### ISSUE TITLE
Implement VGA driver

### ISSUE THREAD

**Issue by steveklabnik** [intermezzOS/kernel#85]
Current status: this has been implemented, but not yet written about in the book.

**Comment by jonhoo** [comment]
Now that https://github.com/intermezzOS/rfcs/pull/8 has been merged, the current implementation in `console/` is likely to be replaced, right? Are we envisioning that the new driver will in any way be related to https://github.com/intermezzOS/vga?

**Comment by steveklabnik** [comment]
Yes, it's going to be replaced. I know it's at the 11th hour, but I think it'll be better for it. 😄 

> Are we envisioning that the new driver will in any way be related to https://github.com/intermezzOS/vga?

IIRC they're basically copies of each other right now, so I expect that one to update in sync with this one.

**Comment by jonhoo** [comment]
Should one be deleted and made to simply point to the other?

**Comment by steveklabnik** [comment]
The idea of that repo is to provide a stand-alone project to get your feet wet; the README and such doesn't do a very good job of explaining that at the moment :(
